//calculate the numbers in the Fibonacci sequence.
//The first two numbers in the Fibonacci sequence are 1 and 1.
//The remaining numbers are generated by adding the previous two numbers.
//So the sequence starts as 1, 1, 2, 3, 5, 8, 13...

/*When the user clicks on the calculate button, this function
should list all of the numbers in the Fibonacci sequence in
order that are lower than one million. */
function calculate() {
    

}